version: '3.8'
services:
  shard1:
    image: "redis:latest"
    ports:
      - "6380:6379"
  timeseries:
    image: "lragji/ts-v2.0"
    depends_on: 
      - "shard1"
    entrypoint: 
      - "node"
      - "service.js"
      - "FILE"
    ports:
      - "80:3000"
    volumes:
      - C:/Users/Lauki/Documents/Git/redis-lsm-timeseries/docker-config/:/usr/src/app/examples/wrap-it-into-microservice/external/
      - C:/Users/Lauki/Documents/Git/redis-lsm-timeseries/docker-config/raw-db/:/usr/src/app/examples/wrap-it-into-microservice/raw-db/
  jmeter:
    image: "justb4/jmeter:latest"
    depends_on: 
      - "timeseries"
    volumes:
      - C:/Users/Lauki/Documents/Git/redis-lsm-timeseries:/app
    working_dir: /app
    entrypoint:
      - "/entrypoint.sh" 
      - "-n" 
      - "-t /app/perf/PerfTest.jmx"
      - "-l /app/perf/jmeter.jtl"
      - "-j /app/perf/jmeter.log"
      - "-f" 
      - "-e" 
      - "-o /app/perf/results"
      - "-JTARGET_HOST=timeseries"
      - "-JTARGET_PORT=3000"
