version: '3.8'
services:
  timeseries:
    image: "lragji/ts-v2.0"
  jmeter:
    image: "justb4/jmeter:latest"
    container_name: jmeter
    depends_on: 
      - "timeseries"
    volumes:
      - ./:/app
    working_dir: /app
    entrypoint:
      - "/entrypoint.sh" 
      - "-n" 
      - "-t /app/PerfTest.jmx"
      - "-l /app/jmeter.jtl"
      - "-j /app/jmeter.log"
      - "-f" 
      - "-e" 
      - "-o /app/results"
      - "-JTARGET_HOST=timeseries"
      - "-JTARGET_PORT=3000"